version: '3.8'

services:
  cms_service:
    image: mysql:8.0
    container_name: cms_service
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cms_db
      MYSQL_USER: cms_user
      MYSQL_PASSWORD: cms_password
    ports:
      - "3306:3306"
    volumes:
      - cms_service_data:/var/lib/mysql

  shofree_service:
    image: mysql:8.0
    container_name: shofree_service
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shofree_db
      MYSQL_USER: shofree_user
      MYSQL_PASSWORD: shofree_password
    ports:
      - "3307:3306"
    volumes:
      - shofree_service_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - cms_service
      - shofree_service

volumes:
  cms_service_data:
    driver: local
  shofree_service_data:
    driver: local
